### ISSUE TITLE
Error define @action in TS if target is es3 (default)

### ISSUE THREAD

**Issue by farwayer** [mobxjs/mobx#1073]
```ts
import {action} from 'mobx'

class User {
  @action login() {}
}

const user = new User();
user.login();
```

```
tsc --experimentalDecorators --target es3 test.ts; node test.js
```

```js
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
exports.__esModule = true;
var mobx_1 = require("mobx");
var User = (function () {
    function User() {
    }
    User.prototype.login = function () { };
    __decorate([
        mobx_1.action
    ], User.prototype, "login");
    return User;
}());
var user = new User();
user.login();
```

```js
/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:991
                Object.defineProperty(target, key, newDescriptor);
                       ^

TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at classPropertyDecorator (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:991:24)
    at /mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1029:64
    at actionName (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1096:43)
    at action (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1075:39)
    at /mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1054:25
    at typescriptInitializeProperty (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:1038:5)
    at User.get (/mnt/data/dev/react/mobx-decorators/node_modules/mobx/lib/mobx.js:975:25)
    at Object.<anonymous> (/mnt/data/dev/react/mobx-decorators/test.js:23:5)
```

**Comment by mweststrate** [comment]
Works for me: http://jsbin.com/gikiguf/edit?js,console

Can you set up a reproduction somewhere? Make sure that you are not importing anything from `mobx/lib/...` directly, only import stuff from `"mobx"`

**Comment by farwayer** [comment]
@mweststrate I was wrong - default target in TS is **es3**. So issue is for **es3** target only.

**Comment by mweststrate** [comment]
MobX doesn't support ES3

Op di 4 jul. 2017 om 12:38 schreef farwayer <notifications@github.com>:

**Comment by mweststrate** [comment]
(Basically, Object.defineProperty does not even exist in ES3)
