### ISSUE TITLE
How to mock observable properties in tests?

### ISSUE THREAD

**Issue by evoyy** [mobxjs/mobx#123]
I'm having some trouble adjusting my test suite for MobX. What is a good way to use mocks with observables?

Initially, I tried to assign the mock to a property, which doesn't work.

````javascript
let obj = mobx.observable({
    a: null,
    b: null,
    c: null,
});

let mock = {
    foo: function() {
        console.log('bar');
    }
};

obj.c = mock;

obj.c.foo();
// TypeError: obj.c.foo is not a function
````

After some experimentation, deleting the property before assigning the mock seemed to work, at least for plain objects. However, with classes I am getting a recursion error:

````javascript
class Obj {
    @observable a
    @observable b
    @observable c

    constructor() {
        this.a = null;
        this.b = null;
        this.c = null;
    }
}

let obj = new Obj();

let mock = {
    foo: function() {
        console.log('bar');
    }
};

delete obj.c;
obj.c = mock;

obj.c.foo();
````

Produces:

````
RangeError: Maximum call stack size exceeded
    at asObservableObject (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1346:28)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:37)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
````

**Comment by evoyy** [comment]
After some experimentation, deleting the property before assigning the mock seemed to work, at least for plain objects. However, with classes I am getting a recursion error:

````javascript
class Obj {
    @observable a
    @observable b
    @observable c

    constructor() {
        this.a = null;
        this.b = null;
        this.c = null;
    }
}

let obj = new Obj();

let mock = {
    foo: function() {
        console.log('bar');
    }
};

delete obj.c;
obj.c = mock;

obj.c.foo();
````

Produces:

````
RangeError: Maximum call stack size exceeded
    at asObservableObject (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1346:28)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:37)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
    at setObservableObjectProperty (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:1371:30)
    at Obj.descriptor.set [as c] (/home/al/sandbox/mobx-test/node_modules/mobx/lib/mobx.js:294:9)
````

**Comment by evoyy** [comment]
As a workaround, I discovered that I can assign mocks in layers, like this:

````javascript
obj.c = { };
obj.c.foo = () => {};
````

This is good enough for now. But I will have a look at the internals and try to understand this library a little better.

**Comment by mweststrate** [comment]
If you want me to dive deeper into it, just let me know. But I rather prefer not too :-D. I have quite the blues from using mocking based testing (especially Jest), it made testing harder for us in generally as mocking makes everything unpredictable, so we dropped Jest before even using mobx. But probably it is fixable :).

**Comment by evoyy** [comment]
No problem since I found a workaround. I don't like to mock if I can avoid it but sometimes I have no choice. For example I am using the soundManager library to load and play audio files, and I need to mock sound.play() etc. Even just stubbing it out with something like {play: () => {}}.
