### ISSUE TITLE
It is not possible to assign a new value to a computed value by delete getter property

### ISSUE THREAD

**Issue by zwhu** [mobxjs/mobx#1884]
Hi,I have an error when I want to delete a getter property:

https://codesandbox.io/s/1y5zn74xn4

```js
import { observable, remove, extendObservable } from "mobx";

let person = observable({
});

extendObservable(person, {
  get name () {return false;}
})


// delete person.name

remove(person, 'name')
```

the stack is:

```js

Error: [mobx] [ComputedValue 'ObservableObject@67.name'] It is not possible to assign a new value to a computed value.
    at invariant$$1 (https://1y5zn74xn4.codesandbox.io/node_modules/mobx/lib/mobx.js:102:15)

    at ComputedValue$$1.set (https://1y5zn74xn4.codesandbox.io/node_modules/mobx/lib/mobx.js:909:13)

    at ObservableObjectAdministration$$1.remove (https://1y5zn74xn4.codesandbox.io/node_modules/mobx/lib/mobx.js:3931:44)

    at remove$$1 (https://1y5zn74xn4.codesandbox.io/node_modules/mobx/lib/mobx.js:2485:23)

    at evaluate (https://1y5zn74xn4.codesandbox.io/index.js:15:18)

    at de (https://codesandbox.io/static/js/sandbox.2c7c8ae5.js:1:157604)

    at e.value (https://codesandbox.io/static/js/sandbox.2c7c8ae5.js:1:171898)

    at e.value (https://codesandbox.io/static/js/sandbox.2c7c8ae5.js:1:199393)

    at e.value (https://codesandbox.io/static/js/sandbox.2c7c8ae5.js:1:199166)

    at https://codesandbox.io/static/js/sandbox.2c7c8ae5.js:1:100087

    at g (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11215)

    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11003)

    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11394)

    at r (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:702)

    at u (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:912)
```

how to resolved this error? thanks.

**Comment by mweststrate** [comment]
Not, computed properties are not allowed to be removed (it would give a false sense of removal and probably be leaking memory). What is your use case for removing a computed property?

**Comment by mweststrate** [comment]
Closing for inactivity
