### ISSUE TITLE
When() is called before constructor

### ISSUE THREAD

**Issue by kachnitel** [mobxjs/mobx#1953]
### **Provide error messages including stacktrace**:
```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[When@1] TypeError: Cannot read property 'id' of undefined
    at eval (https://n316p6yn64.codesandbox.io/index.js:89:30)
    at eval (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3609:13)
    at reactionRunner (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:560:9)
    at trackDerivedFunction (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3256:24)
    at Reaction.track (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3455:22)
    at Reaction.eval [as onInvalidate] (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:541:18)
    at Reaction.runReaction (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3431:22)
    at runReactionsHelper (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3551:35)
    at reactionScheduler (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3529:47)
    at eval (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3558:71)
    at batchedUpdates (https://n316p6yn64.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:13238:14)
    at performFiberBatchedUpdates (https://n316p6yn64.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:1646:10)
    at stackBatchedUpdates (https://n316p6yn64.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:1637:10)
    at batchedUpdates (https://n316p6yn64.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:1651:10)
    at batchedUpdatesWithControlledComponents (https://n316p6yn64.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:1664:12)
    at reactionScheduler (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3558:47)
    at runReactions (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3534:5)
    at Reaction.schedule (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3416:13)
    at autorun (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:562:14)
    at _when (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3608:20)
    at when (https://n316p6yn64.codesandbox.io/node_modules/mobx/lib/mobx.js:3590:12)
    at new AppState (https://n316p6yn64.codesandbox.io/index.js:88:36)
    at evaluate (https://n316p6yn64.codesandbox.io/index.js:133:56)
    at ue (https://codesandbox.io/static/js/sandbox.76505674.js:1:162775)
    at e.value (https://codesandbox.io/static/js/sandbox.76505674.js:1:177478)
    at e.value (https://codesandbox.io/static/js/sandbox.76505674.js:1:205785)
    at e.value (https://codesandbox.io/static/js/sandbox.76505674.js:1:205366)
    at https://codesandbox.io/static/js/sandbox.76505674.js:1:101447
    at g (https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:388846)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:388634)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:389025)
    at t (https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:379282)
    at u (https://codesandbox.io/static/js/common-sandbox.3dc7ca12.chunk.js:1:379492)
```

  ### Provide a **minimal** sample reproduction.: 
https://codesandbox.io/embed/n316p6yn64

  ### Did you check this issue wasn't filed before?
Couldn't find a mention of this issue

  ### Elaborate on your issue. What behavior did you expect?
I would expect a reaction to be initialized **after** the store is initialized in constructor, not throwing an undefined error since the value should be initialized before the reaction.
If I put a console log in the constructor, the error is thrown before any output, confirming it attempts to run the reaction before being constructed.

  ### State the versions of MobX and relevant libraries. Which browser / node / ... version?
```
    "mobx": "^5.9.0",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^5.4.3",

npm -v
6.9.0


    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

```

**Comment by urugator** [comment]
> I would expect a reaction to be initialized after the store is initialized in constructor

Why? Property initializers are invoked before constructor. 
The first callback passed to `when/reaction` runs immediately - so the reaction can react to any state mutation perfromed right after it's created.

**Comment by kachnitel** [comment]
Thanks urugator, I never really thought they would be called before constructor is (generally in any object oriented language), looks like I was mistaken for years as I never really needed to rely on that. 
So if I want to set up a reaction on an object set in constructor, can I define the reaction in constructor?

**Comment by urugator** [comment]
> be called before constructor

It makes the prop values available in constructor, otherwise they would undefined there, which would be even more unfortunate.

> can I define the reaction in constructor

Sure, the:
```javascript 
disposer = when(
  () => this.userState.id,
  () => console.log(this.userState.id)
);    
```
is just a sugar for:
```javascript 
constructor() {
  this.disposer = when(
    () => this.userState.id,
    () => console.log(this.userState.id)
  );      
}    
```
So actually it always happens in constructor, but at it's very beginning.

**Comment by kachnitel** [comment]
Brilliant, thank you! I got it working as I needed, and I'll look further into class initialization!
