### ISSUE TITLE
Add extra Symbol typed keys on ObservableArray causes error

### ISSUE THREAD

**Issue by Mess1ah** [mobxjs/mobx#2044]
Welcome to MobX. Please provide as much relevant information as possible!

I have a:
1. [x] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Provide a **minimal** sample reproduction. **Create a reproduction based on this [sandbox](https://codesandbox.io/s/v3v0my2370)**
  * [x] Did you check this issue wasn't filed before?
  * [ ] Elaborate on your issue. What behavior did you expect?
  * [x]  Mobx Version ^5.11.0, node^8.9.3

stacktrace:
```bash
/yourProjectName/node_modules/mobx/lib/mobx.js:2943
        if (!isNaN(name)) {
             ^

TypeError: Cannot convert a Symbol value to a number
    at isNaN (<anonymous>)
    at Object.set (/yourProjectName/mobx-error-demo/node_modules/mobx/lib/mobx.js:2943:14)
    at Object.<anonymous> (/yourProjectName/index.js:12:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```

sample reproduction: I create a simple repository: [sample](https://github.com/Mess1ah/mobx-error-demo)

When running the conditional sentence `!isNaN(name)`(name is a symbol type variable), It causes an error. It goes well in mobx 4.

**Comment by mweststrate** [comment]
Fixed in 4.13.0 / 5.13.0
