### ISSUE TITLE
To make mobx-undecorate work on windows I had to change some bits in cli.js

### ISSUE THREAD

**Issue by janpieterz** [mobxjs/mobx#2473]
**Intended outcome:**
Run mobx-undecorate on the codebase to easily migrate everything to mobx6.

**Actual outcome:**
ENOENT failures on each run using powershell.

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\.bin\jscodeshift ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node_modules\\.bin\\jscodeshift',
  path: 'node_modules\\.bin\\jscodeshift',
  spawnargs: [
    '--extensions=js,jsx,ts,tsx',
    '-t',
    'src/undecorate.ts',
    'C:\\Development\\DIRECTORY'
  ]
}
```

**How to reproduce the issue:**

Run it on Windows, I guess? Paths with `\` should work fine but it failed to run.

**Fix (but cannot verify this works everywhere)**
*[Pull request](https://github.com/mobxjs/mobx/pull/2472)*

**Comment by mweststrate** [comment]
Released as 1.0.1
