### ISSUE TITLE
Unable to resolve module `./assertEnvironment`

### ISSUE THREAD

**Issue by virtumonde** [mobxjs/mobx#2475]
After upgrading from ```"mobx": "^5.15.7"``` and ```"mobx-react": "^6.3.0"``` to ```"mobx": "^6.0.0"``` and ```"mobx-react": "^7.0.0"``` I receive an ```Unable to resolve module `./assertEnvironment``` error.

## Intended outcome
The app doesn't have any errors

## Actual outcome
```
error: Error: Unable to resolve module `./assertEnvironment` from `node_modules/mobx-react-lite/es/index.js`: 

None of these files exist:
  * node_modules/mobx-react-lite/es/assertEnvironment(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/mobx-react-lite/es/assertEnvironment/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/virtumonde/Desktop/dev/project/project-client/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

## How to reproduce the issue
Install ```"mobx": "^6.0.0"``` and ```"mobx-react": "^7.0.0"``` on ``` "react-native": "0.63.3"```

## Versions
```
"mobx": "^6.0.0",
"mobx-react": "^7.0.0"
"react-native": "0.63.3"
```

**Comment by FredyC** [comment]
Please don't double post, that doesn't help anything. Closing in favor https://github.com/mobxjs/mobx-react/issues/899
