### ISSUE TITLE
mobx-undecorate problem with flow js nullable types

### ISSUE THREAD

**Issue by alexander-schranz** [mobxjs/mobx#2792]
**Intended outcome:**

When I'm running:

```bash
npx mobx-undecorate
```

Inside our project [Sulu CMS](https://github.com/sulu/sulu).

It errors with all files containing nullable object like:

```js
handleChange = (value: Value, media: ?Media) => {
};
```

https://github.com/sulu/sulu/blob/b83b17d66493024af45664fde07a4b5e13196b9d/src/Sulu/Bundle/MediaBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/overlays/MediaInternalLinkTypeOverlay.js#L13

> src/Sulu/Bundle/MediaBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/overlays/MediaInternalLinkTypeOverlay.js Transformation error (Unexpected token (13:41))

**Actual outcome:**

```bash
 ERR /Users/el/Sulu/sulu-develop.localhost/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/js/containers/CKEditor5/plugins/InternalLinkPlugin/overlays/MediaInternalLinkTypeOverlay.js Transformation error (Unexpected token (13:41))
SyntaxError: Unexpected token (13:41)
    at Object._raise (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Object.raiseWithData (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Object.raise (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/error.js:41:17)
    at Object.unexpected (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/parser/util.js:140:16)
    at Object.tsParseNonArrayType (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:866:18)
    at Object.tsParseArrayTypeOrHigher (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:870:23)
    at Object.parseConstituentType [as tsParseTypeOperatorOrHigher] (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:930:16)
    at Object.tsParseUnionOrIntersectionType (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:940:18)
    at Object.parseConstituentType [as tsParseIntersectionTypeOrHigher] (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:953:19)
    at Object.tsParseUnionOrIntersectionType (/Users/el/.npm/_npx/1347/lib/node_modules/mobx-undecorate/node_modules/@babel/parser/src/plugins/typescript/index.js:940:18)
    
Results:
446 errors
0 unmodified
9095 skipped
30 ok
```
    
**How to reproduce the issue:**

```bash
git@github.com:sulu/sulu.git
npx mobx-undecorate
```

**Versions**

As I when using `npx` it will use the latest `mobx-undecorate` version I think.

**Comment by iChenLei** [comment]
#### maybe same as https://github.com/babel/babel/issues/10403

`?<type>` syntax is a flow maybe type. https://flow.org/en/docs/types/maybe/

I think current @babel version that we used not compatiable with it.
```json
{
  "name": "@babel/core",
  "version": "7.12.3",
  "description": "Babel compiler core.",
  "main": "lib/index.js",
```
May be you can skip it when you use `mobx-undecorate` codemod script.

> btw, `flow` is still being adopted is unbelievable to me. Of course, `Reactjs` is still using it.

**Comment by mweststrate** [comment]
We don't officially support flow for MobX. If anybody wants to add an
option to the codemod to support flow parsing, feel free. It might be that
the codemod itself then will need changes as well though, I have no idea
how compatible the ASTs are.

**Comment by alexander-schranz** [comment]
Looks like jscodeshift which is used has an option for `flow` parsing: https://github.com/facebook/jscodeshift maybe we could forward that.

**Comment by mweststrate** [comment]
yeah changing the parser is the easy part, but I assume (not sure) the resulting AST might be different. So it might or might not work out of the box after that :)
