### ISSUE TITLE
toJS fails for observable object with computed value prop

### ISSUE THREAD

**Issue by ahoisl** [mobxjs/mobx#2903]
**Intended outcome:**
toJS converts observable objects with computed value props just fine.

**Actual outcome:**
toJS fails with following exception:

```
TypeError: Cannot read property 'ownKeys_' of undefined
at toJSHelper (node_modules/mobx/src/api/tojs.ts:55:17)
      at propertyIsEnumerable (node_modules/mobx/src/api/tojs.ts:57:14)
          at Array.forEach (<anonymous>)
      at toJSHelper (node_modules/mobx/src/api/tojs.ts:55:33)
      at propertyIsEnumerable (node_modules/mobx/src/api/tojs.ts:57:14)
          at Array.forEach (<anonymous>)
      at toJSHelper (node_modules/mobx/src/api/tojs.ts:55:33)
      at Object.toJS (node_modules/mobx/src/api/tojs.ts:69:2)
```

**How to reproduce the issue:**
Run the following code (-> unit test):
```
const a = observable({ key: "value" });
const c = observable({ computedValue: mobx.computed(() => a.key) });

const j = mobx.toJS(c);
expect(j).toMatchObject({ computedValue: "value" });
```

**Versions**
mobx 6.2.0 (but I guess all previous as well)

**Comment by ahoisl** [comment]
IMHO toJS missed that condition, i.e. computed values as props
