### ISSUE TITLE
eslint-plugin-mobx does not work

### ISSUE THREAD

**Issue by ltdu** [mobxjs/mobx#3199]
I really like the idea of using ```eslint``` to prevent some common / simple issues in code related to ```mobx``` use. However, current version of ```eslint-plugin-mobx``` does not seem to be working at all.

**Intended outcome:**

* Follow installation instructions
* Run ```eslint```
* Receive information that there are some problems with code (or not)

**Actual outcome:**

While installation and configuration of ```eslint-plugin-mobx``` went without any issues, running ```eslint``` produces following message

```cmd
Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "eslint-plugin-mobx".

(The package "eslint-plugin-mobx" was not found when loaded as a Node module from the directory "......\test-eslint-plugin-mobx".)
```

**How to reproduce the issue:**

Just following provided plugin installation steps seems to be enough.

I have reviewed installed module and I think there might be a problem how it was packaged. Just to check that this is not some configuration issue, I *hacked* ```node_modules\eslint-plugin-mobx\package.json``` file by adding following line and plugin was found by ```eslint```:

```
"main": "src/index.js",
```

But now I got another error:

```cmd
Oops! Something went wrong! :(

ESLint: 7.32.0

......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\src\utils.js:20
    error ??= 'Assertion failed';
          ^^^

SyntaxError: Unexpected token '??='
    at new Script (vm.js:102:7)
    at NativeCompileCache._moduleCompile (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\src\exhaustive-make-observable.js:3:43)
    at Module._compile (......\test-eslint-plugin-mobx\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
```

**Comment by urugator** [comment]
Can you please try:
`"main": "dist/index.js"` (instead of `src/index.js`)
and let me know if it does the trick?

**Comment by ltdu** [comment]
That's the thing - ```dist``` does not exist in module folder:

![image](https://user-images.githubusercontent.com/22098043/143702888-063f9937-b91a-45e3-af39-7f2fdd274007.png)

**Comment by urugator** [comment]
Did some changes to `package.json` in #3200. Released as v0.0.3. It may take some time until it will appear on NPM. Let me know if it helped or not.

**Comment by ltdu** [comment]
Reinstalled modules and retrieved updated plugin. Unfortunately, there is still problem with package resolution. This time inside plugin itself:

```
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin 'mobx' declared in '.eslintrc.js': Cannot find module './exhaustive-make-observable.js'
Require stack:
- ......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\dist\eslintpluginmobx.cjs.development.js
- ......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\dist\index.js
- ......\test-eslint-plugin-mobx\node_modules\@eslint\eslintrc\lib\config-array-factory.js
- ......\test-eslint-plugin-mobx\node_modules\@eslint\eslintrc\lib\index.js
- ......\test-eslint-plugin-mobx\node_modules\eslint\lib\cli-engine\cli-engine.js
- ......\test-eslint-plugin-mobx\node_modules\eslint\lib\eslint\eslint.js
- ......\test-eslint-plugin-mobx\node_modules\eslint\lib\eslint\index.js
- ......\test-eslint-plugin-mobx\node_modules\eslint\lib\cli.js
- ......\test-eslint-plugin-mobx\node_modules\eslint\bin\eslint.js
Referenced from: ......\test-eslint-plugin-mobx\.eslintrc.js
```

File ```eslintpluginmobx.cjs.development.js``` tries to import following:

```
'use strict';

var exhaustiveMakeObservable = /*#__PURE__*/require('./exhaustive-make-observable.js');

var unconditionalMakeObservable = /*#__PURE__*/require('./unconditional-make-observable.js');

var missingMakeObservable = /*#__PURE__*/require('./missing-make-observable.js');

module.exports = {
.....
```

None of those files are present in ```dist``` folder. But they are in ```src``` and *hacking* those paths moves me back to 

```
......\test-eslint-plugin-mobx\node_modules\eslint-plugin-mobx\src\utils.js:20
    error ??= 'Assertion failed';
          ^^^
```

**Comment by urugator** [comment]
These `require` shouldn't be there in the first place. I think the transpiler ignores imported `js` files. I will probably need some help with this.

**Comment by ltdu** [comment]
I create [PR](https://github.com/mobxjs/mobx/pull/3201), which *should* solve this problem. I don't know if this is the correct way, and I didn't run any package tests. But I did build and copied ```dist``` folder to my test project for testing. As far as I can tell now it works as expected.

**Comment by urugator** [comment]
I will restate the problem in hope someone could have an idea:
For practical purposes noted in #3201, I would like to keep using `js` + `commonjs` in `eslint-plugin-mobx` package.
Is it feasible with our current build setup using TSDX?
Atm, it leaves `require` calls in the compiled code, intead of stitching the modules together.
cc @mweststrate

**Comment by urugator** [comment]
Released new version, it could still use some work, but should be working now.

It no longer relies on TSDX (we will have to migrate from it sooner or later anyway).

@ltdu let me know if you encounter any issues.

**Comment by ltdu** [comment]
@urugator thank you so much! 

I tried and it works perfectly. There is a small issue of false-positives - we use ```@overide``` decorator from another package - but adding rule ignore on those files solved it.

Great work
