### ISSUE TITLE
`NODE_ENV=test node`: `react-dom` always required in cjs.development entry although specified as optional peer dependency

### ISSUE THREAD

**Issue by kobiburnley** [mobxjs/mobx#3336]
**Intended outcome:**
Running the following commands on terminal should work:

```
npm init
npm install mobx mobx-react-lite react
NODE_ENV=test node -e "require('mobx-react-lite');"
```

**Actual outcome:**
```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'react-dom'
Require stack:
- /Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js
- /Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/node_modules/mobx-react-lite/dist/index.js
- /Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js',
    '/Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/node_modules/mobx-react-lite/dist/index.js',
    '/Users/kobia/IdeaProjects/verticals/mobx-react-lite-test/[eval]'
  ]
}

```

**How to reproduce the issue:**

```
npm init
npm install mobx mobx-react-lite react
NODE_ENV=test node -e "require('mobx-react-lite');"
```

**Versions**

```
{
  "dependencies": {
    "mobx": "^6.4.2",
    "mobx-react-lite": "^3.3.0",
    "react": "^17.0.2"
  }
}
```

**Comment by iChenLei** [comment]
https://nodejs.org/es/blog/npm/peer-dependencies please figure out what is `peer dependencies`

**Comment by mweststrate** [comment]
working as intended indeed, please install react-dom as well.

**Comment by kobiburnley** [comment]
@iChenLei @mweststrate but `react-dom` is not a peer dependency of `mobx-react-lite`

https://github.com/mobxjs/mobx/blob/main/packages/mobx-react-lite/package.json#L40

**Comment by mweststrate** [comment]
It has to have one of the two at least, since some internal React api's need to be hooked up

**Comment by kobiburnley** [comment]
Although this is a rare case, `react-dom` / `react-native` are just 2 common renderers of `react` - but it does not mean those are the only valid renders. 

Since eventually the [`batch` is passed to mobx `configure` ](https://github.com/mobxjs/mobx/blob/72d06f8cd2519ce4dbfb807bc13556ca35866690/packages/mobx-react-lite/src/utils/observerBatching.ts#L16) I think it worth thinking how this can be achieved also without crashing when box `react-dom` / `react-native` are absent
