### ISSUE TITLE
[ERROR] Could not resolve "use-sync-external-store/shim"

### ISSUE THREAD

**Issue by barbalex** [mobxjs/mobx#3666]
I just updated mobx-react-lite from 3.4.3 to 4.0.1 and got this message on the next `npm run dev`:

```console

X [ERROR] Could not resolve "use-sync-external-store/shim"

    node_modules/mobx-react-lite/es/useObserver.js:6:37:
      6 │ import { useSyncExternalStore } from "use-sync-external-store/shim";
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "use-sync-external-store/shim" as external to exclude it from the bundle,
  which will remove this error.

C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/mobx-react-lite/es/useObserver.js:6:37: ERROR: Could not resolve "use-sync-external-store/shim"
    at failureErrorWithLog (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1046:7)
    at C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1058:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:1057:54)
    at handleRequest (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:723:19)
    at handleIncomingPacket (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:745:7)
    at Socket.readFromStdout (C:\Users\alexa\vermehrung\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 37,
        file: 'node_modules/mobx-react-lite/es/useObserver.js',
        length: 30,
        line: 6,
        lineText: 'import { useSyncExternalStore } from "use-sync-external-store/shim";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "use-sync-external-store/shim" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "use-sync-external-store/shim"'
    }
  ],
  warnings: []
}

Node.js v19.4.0
```

**Comment by mweststrate** [comment]
Quick check, with what React version is that? And you are importing as ESM,
correct?

**Comment by BATCOH** [comment]
The package was supposed to have no normal dependencies, and use-sync-external-store would be included in the build.
See [#3590 (comment)](https://github.com/mobxjs/mobx/pull/3590/files/09e471ae4b6b1cc2fc38a9c68e2db90089f6e177#r1060916215)

**Comment by barbalex** [comment]
> with what React version is that?

18.2.0

> you are importing as ESM

yes

**Comment by mweststrate** [comment]
Looking at the shim package setup, having it as a hard dependency rather than bundled has the benefit that build system can decide whether to pick the shim or react 18 implementation, so normal dependency looks correct here.

**Comment by barbalex** [comment]
Not sure if it is important to know but I am using vite (4.2.1)

**Comment by mweststrate** [comment]
Kicked of a new release, 4.0.2 should be available in ~15 minutes, thanks for the PR @tony!

**Comment by barbalex** [comment]
Works.

Thanks a lot to all of you!

**Comment by TechQuery** [comment]
Some bundlers may need additional plugins or options to fix ESM `.js` extension:
- Rollup: https://www.npmjs.com/package/@rollup/plugin-alias
- Vite: https://vite.dev/config/shared-options#resolve-alias
