### ISSUE TITLE
Cannot jest.spyOn a store action MobX 6.9.0

### ISSUE THREAD

**Issue by anthony-kyle** [mobxjs/mobx#3706]
**Intended outcome:**

I have a very basic user store which has an action that saves the user to the database via an HTTP request. Below is the store.

```ts
import { makePersistable } from 'mobx-persist-store';
import { makeAutoObservable } from 'mobx';

class UserStore {
  id: string;

  username: string;

  email: string;

  constructor() {
    makeAutoObservable(this);
    makePersistable(this, {
      name: 'UserStore',
      properties: [
        'id',
        'username',
        'email'
      ],
      storage: window.localStorage,
    });
  }

  set user({
    id,
    username,
    email,
  }) {
    if (id) this.id = id;
    if (username) this.username = username;
    if (email) this.email = email;
  }

  get user() {
    return {
      id: this.id,
      username: this.username,
      email: this.email,
    };
  }

  persistUser = async () => {
    try {
      await httpRequestToStoreUserInDB(this.user)
      return this.user;
    } catch(e) {
      return e;
    }
  }
}

export default UserStore;
```
I have a user form, which on save updates the store and then calls the `persistUser` action to save it to the database.

```ts
const save = async(values) => {
 try {
      userStore.user = {
        id: userStore.id,
        username: values.username,
        email: values.email,
      };
      await userStore.persistUser();

      Notification({
        type: 'success',
        title: 'Changes saved',
      });

      return ({ status: 'success' });
    } catch (error) {
      Notification({
        type: 'error',
        title: 'Sorry, unable to save changes',
        description: 'Please try again.'
      });
      return ({ status: 'error', error });
    }
}
```
When testing the form component I do not wish to make the request and so am attempting to spy and mock the `persistUser` action, so that I can test the component functionality without worrying about if the saving process is successful.

```ts
import React from 'react';
import { render, cleanup, fireEvent, act } from '@testing-library/react';
import { rootStore, StoreProvider } from '../../../stores/Store';
import ManageProfile from '../../../components/accountSettings/ManageProfile';

beforeEach(() => {
  cleanup();
});

const setups = async () => {
  const {
    container,
    baseElement,
    ...utils
  } = render(
    <StoreProvider>
      <ManageProfile />
    </StoreProvider>
  );

  const heading = container.querySelector('h2');
  const main = container.querySelector('main');
  const subheadings = main.querySelectorAll('h3');
  const form = main.querySelector('form');
  const inputs = form.querySelectorAll('input');
  const footer = container.querySelector('footer');
  const button = footer.querySelector('button[type="submit"]');

  return {
    heading,
    main,
    subheadings,
    form,
    inputs,
    footer,
    button,
    baseElement,
    container,
    ...utils,
  };
};

describe('Account Settings: Manage Profile', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });
  
  test('Form submits on valid details', async () => {
    const {
      inputs,
      button
    } = await setups();

    await act(async () => {
      await fireEvent.change(inputs[1], { target: { value: 'Username' } });
      await fireEvent.input(inputs[2], { target: { value: 'test@email.com' } });
      await fireEvent.click(button);
    });

    const persistUserSpy = jest.spyOn(rootStore.userStore, 'persistUser').mockImplementation(async () => ({
      id: '123',
      username: 'testuser',
      email: 'test@test.com'
    }));

    expect(persistUserSpy).toHaveBeenCalled();
  });
});
```

With this I would expect the action to be mocked, so that I can confirm it gets called using the `expect(persistUserSpy).toHaveBeenCalled();` check, and be able to test the functionality I actually wish to test. 

**Actual outcome:**

When I try to run this test, rather than doing the expected, instead I receive an error stating `TypeError: object[methodName].mockImplementation is not a function`

```zsh
 FAIL  src/__tests__/__components_/accountSettings/manageProfile.test.tsx (13.065s)
  Account Settings: Manage Profile
    × Form submits on valid details (169ms)

  ● Account Settings: Manage Profile › Form submits on valid details

    TypeError: object[methodName].mockImplementation is not a function

      335 |     });
      336 |
    > 337 |     const persistUserSpy = jest.spyOn(rootStore.userStore, 'persistUser').mockImplementation(async () => ({
          |                                 ^
      338 |       id: '123',
      339 |       username: 'testuser',
      340 |       email: 'test@test.com'

      at ModuleMockerClass.spyOn (node_modules/jest-mock/build/index.js:865:26)
      at Object.<anonymous> (src/__tests__/__components_/accountSettings/manageProfile.test.tsx:337:33)
```

**How to reproduce the issue:**

The issue can be encountered by using `jest.spyOn('store/path').mockImplementation()` on a store action.

**Versions**
`mobx`:  v6.9.0
`mobx-react`: v6.3.1
`mobx-persist-store`: v1.1.3
`nodejs`: v14.21.3
`react`:  v16.14.0
`typescript: v5.1.3

**Comment by kubk** [comment]
It doesn't look like this issue has anything to do with MobX. I've just tested this simple example, and it works without any issues:

```typescript
class UserStore {
  constructor() {
    makeAutoObservable(this)
  }

  persist(): number {
    return 1;
  }
}

const rootStore = {
  userStore: new UserStore()
}

describe('UpdateStore', () => {
  it('test jest', () => {
    jest.spyOn(rootStore.userStore, 'persist').mockImplementation(() => 2);
    const result = rootStore.userStore.persist();
    expect(result).toBe(2)
  })
})
```

Have you tried removing `makeAutoObservable` or `makePersistable` just to check if the issue persists? If so, it's likely related to Jest or the testing library, not MobX.

**Comment by mweststrate** [comment]
Closing for inactivity
