### ISSUE TITLE
Error on running react test

### ISSUE THREAD

**Issue by suzuki11109** [mobxjs/mobx#405]
I've got and error on running test with enzyme and jest (and also typescript).
But on the web works fine.
It will be error if I render a computed value in the render method.

Here's the error from jest
```
[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These functions should never throw exceptions as MobX will not always be able to recover from them. Please fix the error reported after this message or enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'ExampleState@2.greetings'
[mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These functions should never throw exceptions as MobX will not always be able to recover from them. Please fix the error reported after this message or enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'ExampleView#.render()'
 FAIL  src/components/Example/Example.test.tsx (0.211s)
● ExampleView › it shows buttons
  - Error: [mobx] Invariant failed: Cycle detected in computation ExampleState@2.greetings in 'function () {
                        if (!this.__mobxInitializedProps || this.__mobxInitializedProps[key] !== true)
                            typescriptInitializeProperty(this, key, undefined, onInitialize, customArgs, descriptor_1);
                        return get.call(this, key);
                    }'

```

here's my test
```
describe('ExampleView', () => {
  it('shows buttons', () => {
    let exampleState = new ExampleState();
    const wrapper = shallow(<ExampleView exampleState={exampleState} />);
    // expect(wrapper.find('button').length).toBe(2);
  });
});
```

and here's my code.
```
export class ExampleState {
  @observable name: string = '';

  @computed get greetings(): string {
    return 'Hello my name is ' + this.name;
  }
}

@observer
export class ExampleView extends React.Component<{exampleState: ExampleState}, any> {
  render() {
    return <div>
      <input type="text" value={this.props.exampleState.name}
        onChange={(e: any) => this.props.exampleState.name = e.target.value} />
      <span>{this.props.exampleState.greetings}</span>
    </div>;
  }
}
```
If I remove `<span>{this.props.exampleState.greetings}</span>`, it will be fine.

I have no idea how to fix it 
Could you me for that?
Thanks 😄

**Comment by mweststrate** [comment]
I have no particular (good) experience with Jest. But did you make sure MobX is excluded from stubbing and such? If that didn't help I'll try to set it up as test with enzyme + tape (not gonna burn my fingers anymore on Jest ;-) )

**Comment by mweststrate** [comment]
@suzuki11109 I was able to reproduce this without Jest, with shallow rendering. Will investigate further.

**Comment by suzuki11109** [comment]
Thanks. 
But right now I'm trying on mocha. Looks good for me.

**Comment by mweststrate** [comment]
@suzuki11109 just checked, this issue was fixed in my case by upgrading to the latest mobx / mobx-react. Feel free to reopen the issue if it is not resolved.

**Comment by suzuki11109** [comment]
I've downloaded the latest version and have no luck.
It's still has the same error.
But I think, it's not about shallow rendering.
Even I write test like code below, just access to the computed value, it occurs an error.

```
describe('ExampleStore', () => {
  it('example greetings', () => {
    let store = new ExampleState();
    let ar: string[] = [];

    autorun(() => {
      ar.push(store.greetings); //greetings is computed value. by remove this line, the error is gone
    });
  });
});
```

So I'd like to reopen this issue.

**Comment by andykog** [comment]
@suzuki11109, I have just tried this code with mobx 2.3.6, typescript 1.8.9, it works fine. Does the error occurs if you run this separate piece of code? 
```typescript
import { observable, computed, autorun } from 'mobx';

class ExampleState {
	@observable name: string = '';

	@computed get greetings(): string {
		return 'Hello my name is ' + this.name;
	}
}

let store = new ExampleState();
let ar: string[] = [];

autorun(() => {
	ar.push(store.greetings); //greetings is computed value. by remove this line, the error is gone
});

store.name = "test";

console.log(ar);
```

**Comment by suzuki11109** [comment]
@andykog No, it doesn't. It only occurs when I run in Jest test.

Another thing I just found.
I changed from computed decorator to extendObservable and the test passed. 

```
export class ExampleState {
  @observable name: string = '';
  // @computed get greetings(): string {
  //     return 'Hello my name is ' + this.name;
  // }
  constructor() {
    extendObservable(this, {
      greetings: () => 'Hello my name is ' + this.name
    });
  }
}
```

**Comment by andykog** [comment]
@suzuki11109, did you try `jest.autoMockOff()`?

**Comment by mweststrate** [comment]
@suzuki11109, is there some hot reloading mechanism or similar active?
Existing HMR solutions don't handle decorators very well

Op do 14 jul. 2016 om 17:10 schreef Andy Kogut <notifications@github.com>:

**Comment by suzuki11109** [comment]
@andykog, Yes, I always set autoMock off.

@mweststrate, No, there is no hot reloading. just Jest itself with typescript preprocessor.

**Comment by dmitriid** [comment]
The minimal test case to reproduce this issue (thanks to @mweststrate in #620 )

```
jest.disableAutomock()

import {computed} from 'mobx'

class A {
  @computed get dummy() {
    return 1
  }
}

describe('Dummy', () => {
  it('should not fail', () => {
    const a = new A()
    a.dummy()

    expect(true).toBe(true)
  })
})
```

results in

```
    [mobx] Invariant failed: @computed can only be used on getter functions, like: '@computed get myProps() { return ...; }'. It looks like it was used on a property.

      at invariant (node_modules/mobx/lib/mobx.js:2577:15)
      at observable (node_modules/mobx/lib/mobx.js:229:5)
      at typescriptInitializeProperty (node_modules/mobx/lib/mobx.js:2508:5)
      at A.newDescriptor.get (node_modules/mobx/lib/mobx.js:2453:25)
      at Object.<anonymous> (app/views/__tests__/ticketListView.tsx:28:10)
      at process._tickCallback (node.js:369:9)

```


Here's the relevant setup:

`package.json`

```json
{
  "scripts": {
    "test": "jest",
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.35",
    "@types/react": "^0.14.36",
    "@types/react-dom": "^0.14.17",
    "jest": "16.0.1",
    "typescript": "^2.0.3"
  },
  "dependencies": {
    "mobx": "^2.5.1"
  },
  "jest": {
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "scriptPreprocessor": "./preprocessor.js",
    "testRegex": "/__tests__/.*\\.(ts|tsx|js)$"
  }
}
```

`preprocessor.js`

```js
const fs = require('fs')
const tsc = require('typescript')

// Note: we use the same exact config as for the rest of the project
const fName = tsc.findConfigFile(require('path').dirname(__filename), (path) => {
  try{
    fs.accessSync(path, fs.F_OK)
    return true
  } catch(e) {
    return false
  }
})
const options = tsc.readConfigFile(fName, (f) => fs.readFileSync(f, { encoding: 'utf8' }))
options.exclude = ['node_modules'] // just in case, who knows :)

module.exports = {
  process(src, path) {
    if(path.endsWith('.ts') || path.endsWith('.tsx')){
      return tsc.transpile(
        src,
        options,
        path,
        []
      );
    }
    return src;
  },
};
```

`tsconfig.json`

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": false,
    "experimentalDecorators": true,
    "noLib": false,
    "jsx": "react",
    "outDir": ".build_cache",
    "pretty": true,
    "noEmitOnError": true
  },
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "**/__tests__",
    "**/__mocks__"
  ]
}
```

**Comment by dmitriid** [comment]
More "investigations" using [util](https://nodejs.org/api/util.html). Maybe someone will make sense of this.

This is our class and object

```
class A {
  @observable x = 1

  @computed get computed_dummy(){
    return 1
  }

  get regular_dummy(){
    return 1
  }

  @computed get computed_x(){
    return this.x
  }

  get regular_x(){
    return this.x
  }

  set setX(){
    this.x++
  }
}

const a = new A();
```

Let's inspect our object

```
> console.log(util.inspect(a, {showHidden: true, depth: null, showProxy: true}))

A {
        [__mobxInitializedProps]: { x: true },
        [$mobx]:
         ObservableObjectAdministration {
           target: [Circular],
           name: 'A@1',
           mode: 0,
           values:
            { x:
               ObservableValue {
                 name: 'A@1.x',
                 isPendingUnobservation: true,
                 observers: [ [length]: 0 ],
                 observersIndexes: {},
                 diffValue: 0,
                 lastAccessedBy: 0,
                 lowestObserverState: -1,
                 mode: 0,
                 hasUnreportedChange: false,
                 value: 1 } },
           changeListeners: null,
           interceptors: null },
        x: [Getter/Setter] }
```

Let's see if our properties are there:

```
> console.log(util.inspect(A, {showHidden: true, depth: null, showProxy: true}))

{ [Function: A]
        [length]: 0,
        [name]: 'A',
        [prototype]:
         A {
           [constructor]: [Circular],
           [computed_dummy]: [Getter/Setter],
           regular_dummy: [Getter],
           [computed_x]: [Getter/Setter],
           regular_x: [Getter],
           setX: [Setter],
           x: [Getter/Setter] } }

> for (let key in a) { console.log(key) }
x
regular_dummy
regular_x
setX
```

Not sure if that's what supposed to happen


## 1. Access to _computed_ dummy throws error

```
> console.log(a.computed_dummy)
[mobx] Invariant failed: @computed can only be used on getter functions
```

## 2. Access to _regular_ get dummy is ok

```
> console.log(a.regular_dummy)
1
```

## 3. Access to a _computed_ getter returning an observable value throws an error

```
> console.log(a.computed_x)
[mobx] Invariant failed: @computed can only be used on getter functions
```

## 4. Access to a _regular_ getter returning an observable value throws an error

```
> console.log(a.regular_x)
1
```

## 5. Setting a value in an observable is ok

```
> a.setX++
> console.log(a.regular_x)
2
```

**Comment by mweststrate** [comment]
i thinkyou need to pass `options.compilerOptions` to the transpiler options, instead of all options

**Comment by dmitriid** [comment]
Ah, yes. Good catch. Fixed it, ran again. Same issue still

**Comment by dmitriid** [comment]
Wait, I'll have to re-check that...

**Comment by dmitriid** [comment]
Ah yes. That fixed it!

Thank you!

**Comment by mweststrate** [comment]
yeah run into that a while back as well. Still weird that the compiler doesn't complain about the decorator, but just compiles it differently....
