### ISSUE TITLE
extendObservable fails on object, created with Object.create(null)

### ISSUE THREAD

**Issue by Strate** [mobxjs/mobx#502]
`extendObservable` fails on object, created with `Object.create(null)` wsith error: 
```
TypeError: properties.hasOwnProperty is not a function
      at Object.extendObservableHelper (node_modules/mobx/lib/api/extendobservable.js:30:24)
      at Object.makeChildObservable (node_modules/mobx/lib/types/modifiers.js:124:35)
      at new ObservableValue (node_modules/mobx/lib/types/observablevalue.js:28:34)
      at node_modules/mobx/lib/types/observablemap.js:143:50
```
Seems that lib should use `Object.prototype.hasOwnProperty.call(object, ...)` trick.

**Comment by mweststrate** [comment]
Thanks! will be fixed in next release
