### ISSUE TITLE
Mobx Component Losing State of Decorated Field on Callback from Child Component.

### ISSUE THREAD

**Issue by curtd59** [mobxjs/mobx#911]
ISSUE
  * [X] Issue: Mobx component's  field, example: @observable MyArray[], state is lost on callback to method (function) from child component. All attempts at child components to access parent component functions can be executed, but all local state is 'unassigned'.

STACK TRACE
  * [X] **Provide error messages including stacktrace**
Shows Observed Array "Undefined"

```
embedded:152 Uncaught TypeError: Cannot read property 'splice' of undefined
    at Object.toggleSelection [as onToggleSelection] (eval at transform.run (https://fiddle.jshell.net/js/babel/babel.js:3192:10), <anonymous>:231:31)
    at MyCard._toggle (eval at transform.run (https://fiddle.jshell.net/js/babel/babel.js:3192:10), <anonymous>:117:18)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:9699:16)
    at executeDispatch (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:2807:21)
    at Object.executeDispatchesInOrder (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:2830:5)
    at executeDispatchesAndRelease (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:2270:22)
    at executeDispatchesAndReleaseTopLevel (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:2281:10)
    at Array.forEach (native)
    at forEachAccumulated (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:16141:9)
    at Object.processEventQueue (https://cdnjs.cloudflare.com/ajax/libs/react/0.14.3/react.js:2486:7)
```

FULL DEMO ON JSFIDDLE
  * [X] Provide as much **relevant code**, 
          FULL DEMO OF PROBLEM ON JSFIDDLE 
          HERE: https://jsfiddle.net/ymp1g6qk/3/

SEARCHED BUT UNFOUND
  * [X] Did you check this issue wasn't filed before?

EXPECTED BEHAVIOR: 
  * [X] Elaborate on your issue. What behavior did you expect?
    Is that state is maintained by decorated component and field, and accessible to component 
    functions during events.  I expect state to be preserved by mobx once a decorator is assigned.

CURRENT VERSIONS OF SW VERIFIED TODAY
  * [X] State the versions of MobX and relevant libraries. Which browser / node / ... version?
           Current Chrome Browser, Current React, Mobx-React, Mobx  all verified today.

JSFIDDLE COMPONENT UI
<img width="386" alt="screen shot 2017-03-28 at 12 43 20 pm" src="https://cloud.githubusercontent.com/assets/2743806/24431563/8b2a60b2-13ea-11e7-86f7-fb40fe35ece4.png">

CHROME CONSOLE CONTENTS UPON CLICKING
<img width="765" alt="screen shot 2017-03-28 at 12 37 45 pm" src="https://cloud.githubusercontent.com/assets/2743806/24431569/9816acae-13ea-11e7-8835-d79f5f94a3bd.png">

NOTE: 
1) Console commands: $r.myfunction(myparameter)  work fine, however events do not.

Thanks

**Comment by urugator** [comment]
Line 166, method `toggleSelection` is not bound to `this`. Fix:
```javascript
onToggleSelection={this.toggleSelection.bind(this)}
```

**Comment by mweststrate** [comment]
@curtd59 I assume the above comment fixes the issue? Otherwise feel free to re-open
