### ISSUE TITLE
createTransformers example on gitbook is outdated

### ISSUE THREAD

**Issue by zwhitchcox** [mobxjs/mobx#968]
I have a*:

2. [* ] Issue:
  * [x] **Provide error messages including stacktrace**
  * [x] Did you check this issue wasn't filed before?
  * [x] Elaborate on your issue. What behavior did you expect?
  * [x] State the versions of MobX and relevant libraries. Which browser / node / ... version?

Error:
`
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1116] TypeError: displayFolder.children.filter is not a function
    at eval (eval at <anonymous> (repl:1:1), <anonymous>:55:27)
    at /home/zane/mobx/lib/api/createtransformer.js:26:64
    at Object.trackDerivedFunction (/home/zane/mobx/lib/core/derivation.js:113:20)
    at Transformer.ComputedValue.computeValue (/home/zane/mobx/lib/core/computedvalue.js:131:32)
    at Transformer.ComputedValue.trackAndCompute (/home/zane/mobx/lib/core/computedvalue.js:123:42)
    at Transformer.ComputedValue.get (/home/zane/mobx/lib/core/computedvalue.js:86:26)
    at /home/zane/mobx/lib/api/createtransformer.js:51:36
    at eval (eval at <anonymous> (repl:1:1), <anonymous>:75:18)
    at reactionRunner (/home/zane/mobx/lib/api/autorun.js:28:9)
    at Object.trackDerivedFunction (/home/zane/mobx/lib/core/derivation.js:113:20)
TypeError: Cannot read property 'length' of undefined
    at measure (eval at <anonymous> (repl:1:1), <anonymous>:77:22)
    at measure (eval at <anonymous> (repl:1:1), <anonymous>:6:12)
    at measure (eval at <anonymous> (repl:1:1), <anonymous>:73:3)
    at measure (eval at <anonymous> (repl:1:1), <anonymous>:6:12)
    at eval (eval at <anonymous> (repl:1:1), <anonymous>:70:2)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
`

The example assigns a function to the property in extend observable, which doesn't actually work, although it appears to have been an option at some time in the past.

https://mobx.js.org/refguide/create-transformer.html

https://github.com/mobxjs/mobx/blob/3ea1f4af20a51a1cb30be3e4a55ec8f964a8c495/test/perf/transform-perf.js#L4

Using the newest version of mobx (pulled from git) and node (7.8)

**Comment by urugator** [comment]
Argumentless functions used to be autoconverted into computed, it has been changed so that all getters are autoconverted into computed. 
Thanks for the fix, however could you maybe modify it, so that getters are used instead of explicit `computed`? I think it would be more readable, like this:
```javascript
get name() {
  return this.folder.name;
},
```
(btw assigning function is possible, but it's kept as is)

**Comment by zwhitchcox** [comment]
Right..yeah, I can do that at some point...not sure when though, working on something else rn

**Comment by zwhitchcox** [comment]
Took me forever to figure that out about computed though XD

**Comment by zwhitchcox** [comment]
Yeah, I do like that syntax better

**Comment by zwhitchcox** [comment]
So, is there really any need for `computed` when you can just make a getter like that?

**Comment by zwhitchcox** [comment]
Also, do I need to build before I push the changes?

**Comment by urugator** [comment]
> So, is there really any need for computed

It's used to created standalone boxed computed value: `const boxed = computed(() => o.x + o.y)`

> Also, do I need to build before I push the changes?

dunno

**Comment by zwhitchcox** [comment]
>dunno

Well, it wouldn't build on my machine anyway, so I couldn't...think they're using an old version of gitbook, or maybe there's a bug in gitbook itself, but the newest version of gitbook worked for me.

**Comment by mweststrate** [comment]
Pulled the changes, thanks for the updates! Building is indeed not required, as that would make the PR horrible to read.
